#!/bin/bash

wid=$1
class=$2
instance=$3
fwid=$(bspc query -N -n focused.automatic)
wname=$(xdotool getwindowname "$wid")

if [ "$wname" = "win0" ] || [ -z "$wname" ] || [ "$wname" = " " ] || [ -z "$class" ]
        then
                echo "state=floating"
fi

if [ "$class" = Nightly ]
        then
                if [[ $(xprop -id "$wid" | grep WM_WINDOW_ROLE) = *'= "pop-up"' ]]
                        then
                                echo "state=floating"
                fi
fi
