#!/usr/bin/env bash

count=0
disconnected=""
disconnected1="Nah!"
wireless_connected=""
ethernet_connected=""

ETH_INTERFACE="$(ip -br a | awk '/UP/ {print $1}' | awk '/^e/')"
WLAN_INTERFACE="$(ip -br a | awk '/UP/ {print $1}' | awk '/^w/')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com|| ping -c 1 baidu.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ -n $ETH_INTERFACE ]]; then
            IP="$(ip -br a | awk -v pat="$ETH_INTERFACE" '$0~pat {print $3}' | awk -F '/' '{print $1}')"
            echo "$ethernet_connected $IP"; sleep 25
        elif [[ -n $WLAN_INTERFACE ]]; then
            SSID_NAME=$(iwgetid -r)
            echo "$wireless_connected" "${SSID_NAME}"; sleep 5
        fi
    else
        echo "$disconnected" "$disconnected1"; sleep 0.5
    fi
done
